### PR TITLE
March native option

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by devnexen** [comment]
Proposal to fix https://github.com/microsoft/mimalloc/issues/361

**Comment by rpavlik** [comment]
This would work great, and great default too.

**Comment by baryluk** [comment]
This is ugly and unnecessary (user can already put `-march=native` via C flags). Just remove line 194 to 199.

minmalloc is not a snowflake that is needs to have it in cmake.

**Comment by daanx** [comment]
Hi all -- I want to surely remove `-march=native` by default to support @rpavlik  's case.  I am thinking though that @baryluk  may be right and we should just remove it all together?  Would that be ok @devnexen  or is there a specific use case you had in mind? I remember something about need the flag to build on certain platforms?  
Thanks everyone.

**Comment by devnexen** [comment]
It s mainly useful for platforms like raspberry but not world ending if you insist removing all.

**Comment by daanx** [comment]
Thanks for the reply @devnexen ; I think I will remove it then as I feel the build options are already getting too much ...

**Comment by baryluk** [comment]
> It s mainly useful for platforms like raspberry but not world ending if you insist removing all.

That still doesn't make any sense, because you can still pass `-march=native` manually on raspberry pi just like on any other platform, architecture or system. And every other system equally might want to specialize their compilation to be as fast as possible. It is not a job of the library authors to select all the cpu-specific options, but rather a packagers (where they will select most suitable and compatible options, giving best possible performance) and people who compile it locally (same).

**Pull request closed without merging**
