### PR TITLE
Eliminate '#ifndef' guards

### PR DESCRIPTION
**Pull request by Gymmasssorla**
Related to https://github.com/microsoft/mimalloc/issues/40

### CODE REVIEW

**Comment by santagada** [comment]
This would make distributing compilation and getting mimalloc on precompiled headers more difficult. I wouldn't remove them.

**Comment by daanx** [comment]
Thanks! I am hesitant too to integrate this since now it works on all platforms and I don't want to rely on `#pragma once` in general. Leaving in the extra guard does not hurt (except from a beauty perspective)

**Comment by Gymmasssorla** [comment]
OK, so we will leave the header guards as before and I'll close this pull request?

**Comment by gnzlbg** [comment]
> Thanks! I am hesitant too to integrate this since now it works on all platforms and I don't want to rely on #pragma once in general. Leaving in the extra guard does not hurt (except from a beauty perspective)

What's the argument for using `#pragma once` on top of header guards ? (I thought header guards were enough).

**Comment by mzji** [comment]
> 
> 
> > Thanks! I am hesitant too to integrate this since now it works on all platforms and I don't want to rely on #pragma once in general. Leaving in the extra guard does not hurt (except from a beauty perspective)
> 
> What's the argument for using `#pragma once` on top of header guards ? (I thought header guards were enough).

Check this: https://github.com/microsoft/mimalloc/issues/40#issuecomment-505414005

**Comment by gnzlbg** [comment]
IIUC, that says that pragma once doesn't work in cases where the header guards do work, so it doesn't answer my question. Or am I reading that wrong?

**Comment by daanx** [comment]
Well -- I think we leave this as is for now. Thanks for the discussion!

**Pull request closed without merging**
