### PR TITLE
Add VS solutions that can leverage the MSVC 2019 runtime

### PR DESCRIPTION
**Pull request by kile0**

### CODE REVIEW

**Comment by kile0** [comment]
ONNXRuntime is considering adopting mimalloc, but in order for that to work, we need to be able to build mimalloc on windows under VS2019

**Comment by santagada** [comment]
I think I did that, isn't the case of just opening the solution and retargeting?

**Comment by kile0** [comment]
Yes that works fine as well, but the project I'm trying to integrate it into has mimalloc as a submodule and it'd be nice not to have to add cmake steps to patch the solution on every build

**Comment by daanx** [comment]
Thanks Kirsten! I can't try it out yet but will install vs2019 soon :-)

**Comment by solvingj** [comment]
@kile0 what is the reason you're targeting the visual studio solutions rather than the cmake project? Very curious.

**Pull request merged**
