### PR TITLE
add inline structure definitions for MEM_EXTENDED_PARAMETER2

### PR DESCRIPTION
**Pull request by mrexodia**
This is useful when adding mimalloc with `add_subdirectory` in another project that targets an older SDK version.

### CODE REVIEW

**Comment by daanx** [comment]
Thanks so much! I am hesitant to include such large definitions though.. what I did instead is make the `MEM_EXTENDED_PARAMETER*` a `void*` in the API definition; the actual call is behind an `#ifdef` so this should make it compile on older SDK's as well (just never called, but that's ok :-)). 
It is commit #8ca79b5  -- let me know if that works for you. Best, Daan

**Comment by mrexodia** [comment]
Hi, thanks for the quick reply! Unfortunately this would mean that the VirtualAlloc optimization is not used when *running* under Windows 10. I’m just targeting Windows 8.1 because the build server is for Visual Studio 2015, the final executable is still run under Windows 10 most of the times...

**Comment by daanx** [comment]
Ah, I see! Yes, that is true ... and the new API is actually measurably faster...  feeling quite hesitant though about adding all those definitions. I need to think about it more. Perhaps it is best to skip that call alltogether and use the same optimization that I now use on Linux using allocation in the 4TiB+ address space for large aligned allocations.

**Comment by mrexodia** [comment]
Maybe add some asserts if the Windows original struct is present that the
sizeof() and enum values are the same... Also I checked the commit and saw
that you didn’t change the usage of the new API. Perhaps I didn’t see it
right though.

**Comment by daanx** [comment]
I didn't change the usage but since it is behind an `#ifdef` it will not be used when compiled with an older SDK. 

Another option would be to simplify the struct definition to be just enough for the VirtualAlloc2 call to reduce the clutter...

**Comment by mrexodia** [comment]
I mean, it's what, 50 lines of struct definition? You could probably remove some of the enum cases, but it's not that big of an overhead to be honest.

**Pull request closed without merging**
