### PR TITLE
Heap local deferred free function

### PR DESCRIPTION
**Pull request by playXE**
This PR adds `mi_heap_register_local_deferred_free` function which allows to register deferred free function that is used inside single `mi_heap_t` instance which allows for implementing lazy sweeping in GCs or freeing resources that is associated with mi_heap_t

### CODE REVIEW

**Comment by jserv** [comment]
Can you minimize the patch? That is, no style or indention specific changes.

**Comment by daanx** [comment]
Hi @playXE -- I like the idea of a local deferred free  but the current PR commits are too large (due to whitespace formatting) and also contains references to deleted files. As it is, I cannot clearly see the actual modifications. Perhaps resubmit as a clean PR ?

**Comment by playXE** [comment]
@daanx Hi! I will sent clean commit in a few days. I just do not have time for it because of school. :)

**Comment by playXE** [comment]
I'm going to close this PR and will create new PR when it will be ready.

**Pull request closed without merging**
