### PR TITLE
darwin, tracking anonymous page lifetime.

### PR DESCRIPTION
**Pull request by devnexen**
this platform allows to tag them per application up to 255.

### CODE REVIEW

**Comment by devnexen** [comment]
Allows mmap output as
image

**Comment by jserv** [comment]
I supposed this change is valid to macOS. Can you modify the subject (of Git commit and pull request) as [How to Write a Git Commit Message](https://chris.beams.io/posts/git-commit/) suggested?

**Comment by devnexen** [comment]
In fact Darwin mentions both iOs and macOS but I can always reformulate a little.

**Comment by daanx** [comment]
Great! Thanks so much, I'll pull it in.

**Pull request merged**
