### PR TITLE
Fix wrong reporting of area used bytes

### PR DESCRIPTION
**Pull request by romange**

### CODE REVIEW

**Comment by daanx** [comment]
Thanks so much!

**Comment by res2k** [comment]
Hmm, there was actually a short prior exchange on this in #552 ... too bad it wasn't considered for this PR.

A suggestion there was to use the name `used_bytes` ... it's actually not much longer than `used`, and conveying the unit can be seen as a benefit.
For source compatibility it could be added as a member in addition to `used` - though that wouldn't ABI compatible (should you care about that).
Of course, in case source compatibility isn't promised yet (perhaps the not-quite-stable v2.x branch?) `used` could simply be replaced instead.

**Comment by daanx** [comment]
I remember now why `used` was/is the number of blocks only: when adding padding for debugging it is unclear what the "used" bytes would be: the bytes actually allocated by the user, or the bytes used by the full blocks including padding. 
So, I think best is:

- make `used` be the number of blocks again (and quickly re-release so we keep backward compatibility)
- do not add `used_bytes` 
- for a page visit, the `block_size` is the size available for the user in each block, and the `full_block_size` is the full extent of each block including potential padding/metadata.  
- for each block visit, the passed-in `block_size` is also the page `block_size`.

**Comment by daanx** [comment]
Fixed in commit dev e1b27a0

**Pull request merged**
