### PR TITLE
add/improve atomic yields for SSE2, ARM*, PowerPC

### PR DESCRIPTION
**Pull request by mr-c**

### CODE REVIEW

**Comment by rpavlik** [comment]
I'd like to encourage this to be merged: it fixed the armel build of SolveSpace on Debian, and we'd like to just update to a new upstream version rather than carrying this patch ourselves.

**Comment by devnexen** [comment]
Interesting. Is there any benchmark for the arm64 case ?

**Comment by mr-c** [comment]
> Interesting. Is there any benchmark for the arm64 case (cpu usage, performance)?

I don't have benchmarks, but the `wfe` instruction is how the Linux kernel does atomic yields for their spinlocks  (`arch_spin_lock`) on arm64, arm 32v7, and arm 32v6 with `k` extension

https://sources.debian.org/src/linux/5.10.9-1/arch/arm/include/asm/spinlock.h/?hl=36#L74

the arm64 definition of the `wfe` alias is https://sources.debian.org/src/linux/5.10.9-1/arch/arm64/include/asm/barrier.h/?hl=18#L18
> `#define wfe()		asm volatile("wfe" : : : "memory")`

and the arm (32-bits) definition of the `wfe` alias is https://sources.debian.org/src/linux/5.10.9-1/arch/arm/include/asm/barrier.h/?hl=18#L12
> `#define wfe()	__asm__ __volatile__ ("wfe" : : : "memory")`

**Comment by devnexen** [comment]
true even tough bit_spin_lock, thus cpu_relax use yield on arm64 thus why I was curious about benefits.

Note : I genuinely hope your suggestions are beneficial, it is just to have some background.

**Comment by rpavlik** [comment]
If nothing else, the commit distinguishing versions of ARM in the dev branch were needed to fix armel builds in Debian. Is there a timeline for an upcoming release from dev?

**Comment by vespakoen** [comment]
There is one `(` too many in this PR

I think:
```
(defined(__x86_64__) || defined(__i386__) || (defined(__arm__) || defined(__armel__) || defined(__ARMEL__) || defined(__aarch64__) || defined(__powerpc__) || defined(__ppc__) || defined(__PPC__))
```

Was intended to be:

```
(defined(__x86_64__) || defined(__i386__) || defined(__arm__) || defined(__armel__) || defined(__ARMEL__) || defined(__aarch64__) || defined(__powerpc__) || defined(__ppc__) || defined(__PPC__))
```

Diff for clarity:
```diff
- (defined(__x86_64__) || defined(__i386__) || (defined(__arm__) || defined(__armel__) || defined(__ARMEL__) || defined(__aarch64__) || defined(__powerpc__) || defined(__ppc__) || defined(__PPC__))
+ (defined(__x86_64__) || defined(__i386__) || defined(__arm__) || defined(__armel__) || defined(__ARMEL__) || defined(__aarch64__) || defined(__powerpc__) || defined(__ppc__) || defined(__PPC__))
```

**Comment by daanx** [comment]
@rpavlik: I will merge this now into `dev` (and fix the extra parenthesis @vespakoen -- thanks!).  The plan is to release soon a new version based on dev,  and then soon after a new version based on `dev-slice`. I hope to release a new master with a week depending on how things go.

**Comment by rpavlik** [comment]
great, thanks!

**Comment by mr-c** [comment]
Thanks, all!

**Pull request merged**
